// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: account.sql

package hamed

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    owner,
    balance,
    curreny
) VALUES (
    $1, $2, $3
) RETURNING id, owner, balance, curreny, created_at
`

type CreateAccountParams struct {
	Owner   string
	Balance int64
	Curreny string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Owner, arg.Balance, arg.Curreny)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Curreny,
		&i.CreatedAt,
	)
	return i, err
}
