// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package hamed

import (
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Curreny   string
	CreatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be negative or positive
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// always positive
	Amount    int64
	CreatedAt time.Time
}
